version: "3.9"
services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: unicamp-web
    ports:
      - 80:80
    volumes:
      - ./:/app
    networks:
      network:
        ipv4_address: 10.1.0.4

networks:
    network:
      name: network-mongo
      external: true
